package voxgig.bluefintecsuserbackofficesdk.core

import java.util.{Map => JMap}

import voxgig.bluefintecsuserbackofficesdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  def makeFeature(name: String): Feature = name match {
    case "test" => new voxgig.bluefintecsuserbackofficesdk.feature.TestFeature()
    case _ => new voxgig.bluefintecsuserbackofficesdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsUserBackoffice\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at/usermanagement-backofficews\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"output_activate_digital_module\": {},")
    b.append("   \"output_activate_portal_module\": {},")
    b.append("   \"output_activate_store_module\": {},")
    b.append("   \"output_activate_user\": {},")
    b.append("   \"output_assign_role\": {},")
    b.append("   \"output_change_logo\": {},")
    b.append("   \"output_create_mandator\": {},")
    b.append("   \"output_create_service_user\": {},")
    b.append("   \"output_deactivate_user\": {},")
    b.append("   \"output_get_kyc_document\": {},")
    b.append("   \"output_get_logo\": {},")
    b.append("   \"output_list_of_available_role\": {},")
    b.append("   \"output_list_of_mandator\": {},")
    b.append("   \"output_list_of_module\": {},")
    b.append("   \"output_list_of_role_group\": {},")
    b.append("   \"output_list_of_transactions_history\": {},")
    b.append("   \"output_list_of_user\": {},")
    b.append("   \"output_provide_credential\": {},")
    b.append("   \"output_register_user\": {},")
    b.append("   \"output_remove_role\": {},")
    b.append("   \"output_resend_link\": {},")
    b.append("   \"output_reset_password\": {},")
    b.append("   \"output_update_consumer\": {},")
    b.append("   \"output_update_profile\": {},")
    b.append("   \"version\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"output_activate_digital_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_digital_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateDigitalModule\",")
    b.append("       \"parts\": [")
    b.append("        \"activateDigitalModule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_portal_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"clientSecret\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"notificationEmail\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_portal_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateMerchantPortalModule\",")
    b.append("       \"parts\": [")
    b.append("        \"activateMerchantPortalModule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_store_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_store_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateAppStoreModule\",")
    b.append("       \"parts\": [")
    b.append("        \"activateAppStoreModule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateUser\",")
    b.append("       \"parts\": [")
    b.append("        \"activateUser\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_assign_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"roles\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_assign_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/assignRoles\",")
    b.append("       \"parts\": [")
    b.append("        \"assignRoles\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_change_logo\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"contentAsBase64\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"mimeType\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_change_logo\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/changeLogo\",")
    b.append("       \"parts\": [")
    b.append("        \"changeLogo\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_create_mandator\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"city\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"country\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"description\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"driversLicenseNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"email\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"login\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"name\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phone\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"salutation\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"state\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street1\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street2\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 16")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"zipCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 17")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_create_mandator\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/createMandator\",")
    b.append("       \"parts\": [")
    b.append("        \"createMandator\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_create_service_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"mandatorName\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_create_service_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/createServiceUser\",")
    b.append("       \"parts\": [")
    b.append("        \"createServiceUser\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_deactivate_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_deactivate_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/deactivateUser\",")
    b.append("       \"parts\": [")
    b.append("        \"deactivateUser\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_get_kyc_document\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"caseID\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"encodedDataBase64\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_get_kyc_document\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/getKycDocument\",")
    b.append("       \"parts\": [")
    b.append("        \"getKycDocument\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_get_logo\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"contentAsBase64\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"mimeType\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_get_logo\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/getLogo\",")
    b.append("       \"parts\": [")
    b.append("        \"getLogo\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_available_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"availableRoles\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_available_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfAvailableRoles\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfAvailableRoles\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_mandator\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"filter\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"list\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_mandator\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfMandators\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfMandators\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"list\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfModules\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfModules\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_role_group\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"filter\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"groupRoles\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_role_group\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfRoleGroups\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfRoleGroups\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_transactions_history\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"filter\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"list\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_transactions_history\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfTransactionsHistory\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfTransactionsHistory\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"filter\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"list\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfUsers\",")
    b.append("       \"parts\": [")
    b.append("        \"listOfUsers\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_provide_credential\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"mandatorName\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"password\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"username\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_provide_credential\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/provideCredentials\",")
    b.append("       \"parts\": [")
    b.append("        \"provideCredentials\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_register_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"city\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerId\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerLanguage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"country\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"driverLicenceNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"email\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"login\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"module\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phone\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"salutation\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 16")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"state\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 17")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street1\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 18")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street2\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 19")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"zip\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 20")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_register_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/registerUser\",")
    b.append("       \"parts\": [")
    b.append("        \"registerUser\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_remove_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"roles\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_remove_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/removeRoles\",")
    b.append("       \"parts\": [")
    b.append("        \"removeRoles\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_resend_link\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"businessRegistrationNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"emailConfirmationCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_resend_link\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/resendLink\",")
    b.append("       \"parts\": [")
    b.append("        \"resendLink\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_reset_password\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUuid\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_reset_password\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/resetPassword\",")
    b.append("       \"parts\": [")
    b.append("        \"resetPassword\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_update_consumer\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"city\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerUuid\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerlanguage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"country\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"datetime_created\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"driverLicenceNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"email\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"kycPassed\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$BOOLEAN`\",")
    b.append("     \"index$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"nationality\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"placeOfBirth\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 16")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 17")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"state\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 18")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street1\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 19")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"street2\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 20")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transactionhistory_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 21")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"zip\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 22")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_update_consumer\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/updateConsumer\",")
    b.append("       \"parts\": [")
    b.append("        \"updateConsumer\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_update_profile\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"consumerLanguage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"email\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$INTEGER`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_update_profile\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/updateProfile\",")
    b.append("       \"parts\": [")
    b.append("        \"updateProfile\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"version\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"appName\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"buildDate\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"version\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"version\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/version\",")
    b.append("       \"parts\": [")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
