-- BluefinTecsUserBackoffice SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Output_activate_digital_module
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_activate_digital_module" d co
end Output_activate_digital_module

namespace Output_activate_portal_module
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_activate_portal_module" d co
end Output_activate_portal_module

namespace Output_activate_store_module
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_activate_store_module" d co
end Output_activate_store_module

namespace Output_activate_user
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_activate_user" d co
end Output_activate_user

namespace Output_assign_role
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_assign_role" d co
end Output_assign_role

namespace Output_change_logo
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_change_logo" d co
end Output_change_logo

namespace Output_create_mandator
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_create_mandator" d co
end Output_create_mandator

namespace Output_create_service_user
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_create_service_user" d co
end Output_create_service_user

namespace Output_deactivate_user
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_deactivate_user" d co
end Output_deactivate_user

namespace Output_get_kyc_document
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_get_kyc_document" d co
end Output_get_kyc_document

namespace Output_get_logo
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "output_get_logo" m co
end Output_get_logo

namespace Output_list_of_available_role
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_available_role" d co
end Output_list_of_available_role

namespace Output_list_of_mandator
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_mandator" d co
end Output_list_of_mandator

namespace Output_list_of_module
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_module" d co
end Output_list_of_module

namespace Output_list_of_role_group
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_role_group" d co
end Output_list_of_role_group

namespace Output_list_of_transactions_history
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_transactions_history" d co
end Output_list_of_transactions_history

namespace Output_list_of_user
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list_of_user" d co
end Output_list_of_user

namespace Output_provide_credential
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_provide_credential" d co
end Output_provide_credential

namespace Output_register_user
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_register_user" d co
end Output_register_user

namespace Output_remove_role
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_remove_role" d co
end Output_remove_role

namespace Output_resend_link
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_resend_link" d co
end Output_resend_link

namespace Output_reset_password
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_reset_password" d co
end Output_reset_password

namespace Output_update_consumer
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_update_consumer" d co
end Output_update_consumer

namespace Output_update_profile
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_update_profile" d co
end Output_update_profile

namespace Version
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "version" m co
end Version

