// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinTecsUserBackoffice")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://test.tecs.at/usermanagement-backofficews"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(25,
        "output_activate_digital_module", v_map(),
        "output_activate_portal_module", v_map(),
        "output_activate_store_module", v_map(),
        "output_activate_user", v_map(),
        "output_assign_role", v_map(),
        "output_change_logo", v_map(),
        "output_create_mandator", v_map(),
        "output_create_service_user", v_map(),
        "output_deactivate_user", v_map(),
        "output_get_kyc_document", v_map(),
        "output_get_logo", v_map(),
        "output_list_of_available_role", v_map(),
        "output_list_of_mandator", v_map(),
        "output_list_of_module", v_map(),
        "output_list_of_role_group", v_map(),
        "output_list_of_transactions_history", v_map(),
        "output_list_of_user", v_map(),
        "output_provide_credential", v_map(),
        "output_register_user", v_map(),
        "output_remove_role", v_map(),
        "output_resend_link", v_map(),
        "output_reset_password", v_map(),
        "output_update_consumer", v_map(),
        "output_update_profile", v_map(),
        "version", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(25,
      "output_activate_digital_module", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("output_activate_digital_module"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/activateDigitalModule"),
                "parts", clist(1,
                  v_str("activateDigitalModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_portal_module", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client_secret"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("notification_email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_activate_portal_module"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/activateMerchantPortalModule"),
                "parts", clist(1,
                  v_str("activateMerchantPortalModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_store_module", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("output_activate_store_module"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/activateAppStoreModule"),
                "parts", clist(1,
                  v_str("activateAppStoreModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_activate_user"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/activateUser"),
                "parts", clist(1,
                  v_str("activateUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_assign_role", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("role"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(3))),
        "name", v_str("output_assign_role"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/assignRoles"),
                "parts", clist(1,
                  v_str("assignRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_change_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("content_as_base64"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mime_type"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_change_logo"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/changeLogo"),
                "parts", clist(1,
                  v_str("changeLogo")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_mandator", cmap(4,
        "fields", clist(21,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("date_of_birth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("description"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("drivers_license_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identification_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("login"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandator"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passport_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("salutation"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zip_code"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20))),
        "name", v_str("output_create_mandator"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/createMandator"),
                "parts", clist(1,
                  v_str("createMandator")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_service_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandator_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_create_service_user"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/createServiceUser"),
                "parts", clist(1,
                  v_str("createServiceUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_deactivate_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_deactivate_user"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/deactivateUser"),
                "parts", clist(1,
                  v_str("deactivateUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_kyc_document", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("case_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("encoded_data_base64"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_get_kyc_document"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/getKycDocument"),
                "parts", clist(1,
                  v_str("getKycDocument")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("content_as_base64"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mime_type"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_get_logo"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/getLogo"),
                "parts", clist(1,
                  v_str("getLogo")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_available_role", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("available_role"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_list_of_available_role"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfAvailableRoles"),
                "parts", clist(1,
                  v_str("listOfAvailableRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_mandator", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_mandator"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfMandators"),
                "parts", clist(1,
                  v_str("listOfMandators")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_module", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_list_of_module"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfModules"),
                "parts", clist(1,
                  v_str("listOfModules")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_role_group", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("group_role"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_role_group"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfRoleGroups"),
                "parts", clist(1,
                  v_str("listOfRoleGroups")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_transactions_history", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_transactions_history"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfTransactionsHistory"),
                "parts", clist(1,
                  v_str("listOfTransactionsHistory")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_user", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_user"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/listOfUsers"),
                "parts", clist(1,
                  v_str("listOfUsers")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_provide_credential", cmap(4,
        "fields", clist(5,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandator_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("password"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("username"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4))),
        "name", v_str("output_provide_credential"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/provideCredentials"),
                "parts", clist(1,
                  v_str("provideCredentials")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_register_user", cmap(4,
        "fields", clist(21,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_language"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("date_of_birth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("driver_licence_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identification_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("login"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("module"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passport_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("salutation"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zip"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20))),
        "name", v_str("output_register_user"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/registerUser"),
                "parts", clist(1,
                  v_str("registerUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_role", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("role"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(3))),
        "name", v_str("output_remove_role"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/removeRoles"),
                "parts", clist(1,
                  v_str("removeRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_resend_link", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("business_registration_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email_confirmation_code"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5))),
        "name", v_str("output_resend_link"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/resendLink"),
                "parts", clist(1,
                  v_str("resendLink")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_reset_password", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_reset_password"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/resetPassword"),
                "parts", clist(1,
                  v_str("resetPassword")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_consumer", cmap(4,
        "fields", clist(23,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerlanguage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("date_of_birth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("datetime_created"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("driver_licence_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identification_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("kyc_passed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("nationality"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passport_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("place_of_birth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transactionhistory_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(21)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zip"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(22))),
        "name", v_str("output_update_consumer"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/updateConsumer"),
                "parts", clist(1,
                  v_str("updateConsumer")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_profile", cmap(4,
        "fields", clist(7,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_language"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("first_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("last_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6))),
        "name", v_str("output_update_profile"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/updateProfile"),
                "parts", clist(1,
                  v_str("updateProfile")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "version", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("app_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("build_date"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("version"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("GET"),
                "orig", v_str("/version"),
                "parts", clist(1,
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "cache") == 0) return feature_cache_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "netsim") == 0) return feature_netsim_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "proxy") == 0) return feature_proxy_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "rbac") == 0) return feature_rbac_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "streaming") == 0) return feature_streaming_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}
