// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinTecsUserBackoffice")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://test.tecs.at/usermanagement-backofficews"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(25,
        "output_activate_digital_module", v_map(),
        "output_activate_portal_module", v_map(),
        "output_activate_store_module", v_map(),
        "output_activate_user", v_map(),
        "output_assign_role", v_map(),
        "output_change_logo", v_map(),
        "output_create_mandator", v_map(),
        "output_create_service_user", v_map(),
        "output_deactivate_user", v_map(),
        "output_get_kyc_document", v_map(),
        "output_get_logo", v_map(),
        "output_list_of_available_role", v_map(),
        "output_list_of_mandator", v_map(),
        "output_list_of_module", v_map(),
        "output_list_of_role_group", v_map(),
        "output_list_of_transactions_history", v_map(),
        "output_list_of_user", v_map(),
        "output_provide_credential", v_map(),
        "output_register_user", v_map(),
        "output_remove_role", v_map(),
        "output_resend_link", v_map(),
        "output_reset_password", v_map(),
        "output_update_consumer", v_map(),
        "output_update_profile", v_map(),
        "version", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(25,
      "output_activate_digital_module", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("output_activate_digital_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateDigitalModule"),
                "parts", clist(1,
                  v_str("activateDigitalModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_portal_module", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("clientSecret"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("notificationEmail"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_activate_portal_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateMerchantPortalModule"),
                "parts", clist(1,
                  v_str("activateMerchantPortalModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_store_module", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("output_activate_store_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateAppStoreModule"),
                "parts", clist(1,
                  v_str("activateAppStoreModule")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUUID"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_activate_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateUser"),
                "parts", clist(1,
                  v_str("activateUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_assign_role", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("roles"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(3))),
        "name", v_str("output_assign_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/assignRoles"),
                "parts", clist(1,
                  v_str("assignRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_change_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("contentAsBase64"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mimeType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_change_logo"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/changeLogo"),
                "parts", clist(1,
                  v_str("changeLogo")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_mandator", cmap(4,
        "fields", clist(18,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("dateOfBirth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("description"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("driversLicenseNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firstName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identificationNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("lastName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("login"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("name"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passportNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("salutation"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zipCode"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17))),
        "name", v_str("output_create_mandator"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/createMandator"),
                "parts", clist(1,
                  v_str("createMandator")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_service_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandatorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_create_service_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/createServiceUser"),
                "parts", clist(1,
                  v_str("createServiceUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_deactivate_user", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUUID"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_deactivate_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/deactivateUser"),
                "parts", clist(1,
                  v_str("deactivateUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_kyc_document", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("caseID"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("encodedDataBase64"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_get_kyc_document"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/getKycDocument"),
                "parts", clist(1,
                  v_str("getKycDocument")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("contentAsBase64"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mimeType"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_get_logo"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/getLogo"),
                "parts", clist(1,
                  v_str("getLogo")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_available_role", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("availableRoles"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_list_of_available_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfAvailableRoles"),
                "parts", clist(1,
                  v_str("listOfAvailableRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_mandator", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_mandator"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfMandators"),
                "parts", clist(1,
                  v_str("listOfMandators")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_module", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_list_of_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfModules"),
                "parts", clist(1,
                  v_str("listOfModules")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_role_group", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("groupRoles"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_role_group"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfRoleGroups"),
                "parts", clist(1,
                  v_str("listOfRoleGroups")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_transactions_history", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_transactions_history"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfTransactionsHistory"),
                "parts", clist(1,
                  v_str("listOfTransactionsHistory")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_user", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("list"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5))),
        "name", v_str("output_list_of_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfUsers"),
                "parts", clist(1,
                  v_str("listOfUsers")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_provide_credential", cmap(4,
        "fields", clist(5,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandatorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("password"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("username"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4))),
        "name", v_str("output_provide_credential"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/provideCredentials"),
                "parts", clist(1,
                  v_str("provideCredentials")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_register_user", cmap(4,
        "fields", clist(21,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerId"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerLanguage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("dateOfBirth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("driverLicenceNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firstName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identificationNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("lastName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("login"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("module"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passportNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("salutation"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zip"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20))),
        "name", v_str("output_register_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/registerUser"),
                "parts", clist(1,
                  v_str("registerUser")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_role", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUUID"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("roles"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(3))),
        "name", v_str("output_remove_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/removeRoles"),
                "parts", clist(1,
                  v_str("removeRoles")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_resend_link", cmap(4,
        "fields", clist(6,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("businessRegistrationNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("emailConfirmationCode"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phoneNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5))),
        "name", v_str("output_resend_link"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/resendLink"),
                "parts", clist(1,
                  v_str("resendLink")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_reset_password", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phoneNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_reset_password"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/resetPassword"),
                "parts", clist(1,
                  v_str("resetPassword")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_consumer", cmap(4,
        "fields", clist(23,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerUuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerlanguage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("dateOfBirth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("datetime_created"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("driverLicenceNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firstName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("identificationNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("kycPassed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("lastName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("nationality"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("passportNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phoneNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("placeOfBirth"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street1"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transactionhistory_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(21)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zip"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(22))),
        "name", v_str("output_update_consumer"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/updateConsumer"),
                "parts", clist(1,
                  v_str("updateConsumer")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_profile", cmap(4,
        "fields", clist(7,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumerLanguage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firstName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("lastName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phoneNumber"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseCode"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("responseMessage"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6))),
        "name", v_str("output_update_profile"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/updateProfile"),
                "parts", clist(1,
                  v_str("updateProfile")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "version", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("appName"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("buildDate"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("version"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("version"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/version"),
                "parts", clist(1,
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
