// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinTecsUserBackoffice"),
      "slug", v_str("bluefin-tecs-user-backoffice"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(12,
      "audit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "actor", v_str("anonymous"),
          "max", v_num(1000)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sink", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "clienttrack", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "clientVersion", v_str("0.0.1")),
        "optspec", cmap(5,
          "clientName", v_str("`$STRING`"),
          "clientVersion", v_str("`$STRING`"),
          "headers", v_str("`$MAP`"),
          "idgen", v_str("`$FUNCTION`"),
          "sessionId", v_str("`$STRING`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "log", cmap(4,
        "options", cmap(1,
          "active", v_bool(true)),
        "optspec", cmap(2,
          "level", v_str("`$STRING`"),
          "logger", v_str("`$ANY`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "telemetry", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(4,
          "exporter", v_str("`$FUNCTION`"),
          "headers", v_str("`$MAP`"),
          "idgen", v_str("`$FUNCTION`"),
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://test.tecs.at/usermanagement-backofficews"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(25,
        "output_activate_digital_module", v_map(),
        "output_activate_portal_module", v_map(),
        "output_activate_store_module", v_map(),
        "output_activate_user", v_map(),
        "output_assign_role", v_map(),
        "output_change_logo", v_map(),
        "output_create_mandator", v_map(),
        "output_create_service_user", v_map(),
        "output_deactivate_user", v_map(),
        "output_get_kyc_document", v_map(),
        "output_get_logo", v_map(),
        "output_list_of_available_role", v_map(),
        "output_list_of_mandator", v_map(),
        "output_list_of_module", v_map(),
        "output_list_of_role_group", v_map(),
        "output_list_of_transactions_history", v_map(),
        "output_list_of_user", v_map(),
        "output_provide_credential", v_map(),
        "output_register_user", v_map(),
        "output_remove_role", v_map(),
        "output_resend_link", v_map(),
        "output_reset_password", v_map(),
        "output_update_consumer", v_map(),
        "output_update_profile", v_map(),
        "version", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(25,
      "output_activate_digital_module", cmap(4,
        "fields", clist(2,
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_activate_digital_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateDigitalModule"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("activateDigitalModule"))),
                "parts", clist(1,
                  v_str("activateDigitalModule")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_portal_module", cmap(4,
        "fields", clist(4,
          cmap(4,
            "name", v_str("clientSecret"),
            "title", v_str("Client Secret"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("notificationEmail"),
            "title", v_str("Notification Email"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_activate_portal_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateMerchantPortalModule"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("activateMerchantPortalModule"))),
                "parts", clist(1,
                  v_str("activateMerchantPortalModule")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_store_module", cmap(4,
        "fields", clist(2,
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_activate_store_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateAppStoreModule"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("activateAppStoreModule"))),
                "parts", clist(1,
                  v_str("activateAppStoreModule")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_activate_user", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("consumerUUID"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_activate_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/activateUser"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("activateUser"))),
                "parts", clist(1,
                  v_str("activateUser")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_assign_role", cmap(4,
        "fields", clist(4,
          cmap(5,
            "name", v_str("consumerUUID"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("Unique identifier of the consumer (user) to whom the role(s) will be assigned.")),
          cmap(5,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Response code: 0 indicates success; any non-zero value indicates an error."),
            "format", v_str("int32")),
          cmap(4,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"),
            "short", v_str("A human-readable message providing additional details about the outcome.")),
          cmap(5,
            "name", v_str("roles"),
            "title", v_str("Roles"),
            "type", v_str("`$ARRAY`"),
            "req", v_bool(true),
            "short", v_str("List of roles to assign to the consumer."))),
        "name", v_str("output_assign_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/assignRoles"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("assignRoles"))),
                "parts", clist(1,
                  v_str("assignRoles")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_change_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "name", v_str("contentAsBase64"),
            "title", v_str("Content As Base64"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("The content of the image as base64 encoded string")),
          cmap(5,
            "name", v_str("mimeType"),
            "title", v_str("Mime Type"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("The MIME type of the image")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_change_logo"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/changeLogo"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("changeLogo"))),
                "parts", clist(1,
                  v_str("changeLogo")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_mandator", cmap(4,
        "fields", clist(18,
          cmap(3,
            "name", v_str("city"),
            "title", v_str("City"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("country"),
            "title", v_str("Country"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("dateOfBirth"),
            "title", v_str("Date Of Birth"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("description"),
            "title", v_str("Description"),
            "type", v_str("`$STRING`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`")))),
          cmap(3,
            "name", v_str("driversLicenseNumber"),
            "title", v_str("Drivers License Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(3,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("identificationNumber"),
            "title", v_str("Identification Number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("login"),
            "title", v_str("Login"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`")))),
          cmap(3,
            "name", v_str("passportNumber"),
            "title", v_str("Passport Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("phone"),
            "title", v_str("Phone"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(3,
            "name", v_str("salutation"),
            "title", v_str("Salutation"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("state"),
            "title", v_str("State"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street1"),
            "title", v_str("Street1"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street2"),
            "title", v_str("Street2"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("zipCode"),
            "title", v_str("Zip Code"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_create_mandator"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/createMandator"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("createMandator"))),
                "parts", clist(1,
                  v_str("createMandator")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.mandator`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_service_user", cmap(4,
        "fields", clist(3,
          cmap(4,
            "name", v_str("mandatorName"),
            "title", v_str("Mandator Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_create_service_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/createServiceUser"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("createServiceUser"))),
                "parts", clist(1,
                  v_str("createServiceUser")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_deactivate_user", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("consumerUUID"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_deactivate_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/deactivateUser"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("deactivateUser"))),
                "parts", clist(1,
                  v_str("deactivateUser")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_kyc_document", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("caseID"),
            "title", v_str("Case Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("encodedDataBase64"),
            "title", v_str("Encoded Data Base64"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_get_kyc_document"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/getKycDocument"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("getKycDocument"))),
                "parts", clist(1,
                  v_str("getKycDocument")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_get_logo", cmap(4,
        "fields", clist(4,
          cmap(5,
            "name", v_str("contentAsBase64"),
            "title", v_str("Content As Base64"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("The content of the image as base64 encoded string")),
          cmap(5,
            "name", v_str("mimeType"),
            "title", v_str("Mime Type"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("The MIME type of the image")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_get_logo"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/getLogo"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("getLogo"))),
                "parts", clist(1,
                  v_str("getLogo")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_available_role", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("availableRoles"),
            "title", v_str("Available Roles"),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_list_of_available_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfAvailableRoles"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfAvailableRoles"))),
                "parts", clist(1,
                  v_str("listOfAvailableRoles")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_mandator", cmap(4,
        "fields", clist(6,
          cmap(3,
            "name", v_str("filter"),
            "title", v_str("Filter"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("list"),
            "title", v_str("List"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("pagination"),
            "title", v_str("Pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sorting"),
            "title", v_str("Sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list_of_mandator"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfMandators"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfMandators"))),
                "parts", clist(1,
                  v_str("listOfMandators")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_module", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("list"),
            "title", v_str("List"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("pagination"),
            "title", v_str("Pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_list_of_module"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfModules"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfModules"))),
                "parts", clist(1,
                  v_str("listOfModules")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_role_group", cmap(4,
        "fields", clist(6,
          cmap(3,
            "name", v_str("filter"),
            "title", v_str("Filter"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("groupRoles"),
            "title", v_str("Group Roles"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("pagination"),
            "title", v_str("Pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sorting"),
            "title", v_str("Sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list_of_role_group"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfRoleGroups"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfRoleGroups"))),
                "parts", clist(1,
                  v_str("listOfRoleGroups")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_transactions_history", cmap(4,
        "fields", clist(6,
          cmap(3,
            "name", v_str("filter"),
            "title", v_str("Filter"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("list"),
            "title", v_str("List"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("pagination"),
            "title", v_str("Pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sorting"),
            "title", v_str("Sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list_of_transactions_history"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfTransactionsHistory"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfTransactionsHistory"))),
                "parts", clist(1,
                  v_str("listOfTransactionsHistory")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list_of_user", cmap(4,
        "fields", clist(6,
          cmap(3,
            "name", v_str("filter"),
            "title", v_str("Filter"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("list"),
            "title", v_str("List"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("pagination"),
            "title", v_str("Pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sorting"),
            "title", v_str("Sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list_of_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/listOfUsers"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("listOfUsers"))),
                "parts", clist(1,
                  v_str("listOfUsers")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_provide_credential", cmap(4,
        "fields", clist(5,
          cmap(4,
            "name", v_str("mandatorName"),
            "title", v_str("Mandator Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(3,
            "name", v_str("password"),
            "title", v_str("Password"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("username"),
            "title", v_str("Username"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_provide_credential"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/provideCredentials"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("provideCredentials"))),
                "parts", clist(1,
                  v_str("provideCredentials")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_register_user", cmap(4,
        "fields", clist(21,
          cmap(4,
            "name", v_str("city"),
            "title", v_str("City"),
            "type", v_str("`$STRING`"),
            "short", v_str("City where the user resides.")),
          cmap(4,
            "name", v_str("consumerId"),
            "title", v_str("Consumer Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("User login or unique user identifier.")),
          cmap(4,
            "name", v_str("consumerLanguage"),
            "title", v_str("Consumer Language"),
            "type", v_str("`$STRING`"),
            "short", v_str("Preferred language for the user (e.g., 'en').")),
          cmap(4,
            "name", v_str("country"),
            "title", v_str("Country"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's country.")),
          cmap(4,
            "name", v_str("dateOfBirth"),
            "title", v_str("Date Of Birth"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's date of birth (expected format: dd.MM.yyyy).")),
          cmap(4,
            "name", v_str("driverLicenceNumber"),
            "title", v_str("Driver Licence Number"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's driver's license number.")),
          cmap(6,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true),
            "short", v_str("User's email address (must be unique)."),
            "format", v_str("email")),
          cmap(4,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's first name.")),
          cmap(4,
            "name", v_str("identificationNumber"),
            "title", v_str("Identification Number"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's identification number.")),
          cmap(4,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's last name.")),
          cmap(4,
            "name", v_str("login"),
            "title", v_str("Login"),
            "type", v_str("`$STRING`"),
            "short", v_str("User login identifier (should be unique).")),
          cmap(4,
            "name", v_str("module"),
            "title", v_str("Module"),
            "type", v_str("`$STRING`"),
            "short", v_str("Module identifier (if applicable).")),
          cmap(4,
            "name", v_str("passportNumber"),
            "title", v_str("Passport Number"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's passport number.")),
          cmap(4,
            "name", v_str("phone"),
            "title", v_str("Phone"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's phone number.")),
          cmap(5,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Response code (0 indicates success; non-zero indicates an error)."),
            "format", v_str("int32")),
          cmap(4,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"),
            "short", v_str("Human-readable response message.")),
          cmap(4,
            "name", v_str("salutation"),
            "title", v_str("Salutation"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's salutation (e.g., Mr., Ms.).")),
          cmap(4,
            "name", v_str("state"),
            "title", v_str("State"),
            "type", v_str("`$STRING`"),
            "short", v_str("User's state or region.")),
          cmap(4,
            "name", v_str("street1"),
            "title", v_str("Street1"),
            "type", v_str("`$STRING`"),
            "short", v_str("Primary address line.")),
          cmap(4,
            "name", v_str("street2"),
            "title", v_str("Street2"),
            "type", v_str("`$STRING`"),
            "short", v_str("Secondary address line.")),
          cmap(4,
            "name", v_str("zip"),
            "title", v_str("Zip"),
            "type", v_str("`$STRING`"),
            "short", v_str("Postal code."))),
        "name", v_str("output_register_user"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/registerUser"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("registerUser"))),
                "parts", clist(1,
                  v_str("registerUser")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_role", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("consumerUUID"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("roles"),
            "title", v_str("Roles"),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("output_remove_role"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/removeRoles"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("removeRoles"))),
                "parts", clist(1,
                  v_str("removeRoles")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_resend_link", cmap(4,
        "fields", clist(6,
          cmap(3,
            "name", v_str("businessRegistrationNumber"),
            "title", v_str("Business Registration Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("consumerUUID"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(3,
            "name", v_str("emailConfirmationCode"),
            "title", v_str("Email Confirmation Code"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "title", v_str("Phone Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_resend_link"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/resendLink"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("resendLink"))),
                "parts", clist(1,
                  v_str("resendLink")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(4,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header")))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_reset_password", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("consumerUuid"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "title", v_str("Phone Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_reset_password"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/resetPassword"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("resetPassword"))),
                "parts", clist(1,
                  v_str("resetPassword")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_consumer", cmap(4,
        "fields", clist(23,
          cmap(3,
            "name", v_str("city"),
            "title", v_str("City"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("consumerUuid"),
            "title", v_str("Consumer Uuid"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(3,
            "name", v_str("consumerlanguage"),
            "title", v_str("Consumerlanguage"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("country"),
            "title", v_str("Country"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("dateOfBirth"),
            "title", v_str("Date Of Birth"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("datetime_created"),
            "title", v_str("Datetime Created"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("driverLicenceNumber"),
            "title", v_str("Driver Licence Number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("identificationNumber"),
            "title", v_str("Identification Number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("kycPassed"),
            "title", v_str("Kyc Passed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("nationality"),
            "title", v_str("Nationality"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("passportNumber"),
            "title", v_str("Passport Number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "title", v_str("Phone Number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("placeOfBirth"),
            "title", v_str("Place Of Birth"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("state"),
            "title", v_str("State"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street1"),
            "title", v_str("Street1"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street2"),
            "title", v_str("Street2"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("transactionhistory_id"),
            "title", v_str("Transactionhistory Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("zip"),
            "title", v_str("Zip"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_update_consumer"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/updateConsumer"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("updateConsumer"))),
                "parts", clist(1,
                  v_str("updateConsumer")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(4,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header")))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_profile", cmap(4,
        "fields", clist(7,
          cmap(3,
            "name", v_str("consumerLanguage"),
            "title", v_str("Consumer Language"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("email"),
            "title", v_str("Email"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("firstName"),
            "title", v_str("First Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("lastName"),
            "title", v_str("Last Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "title", v_str("Phone Number"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("responseCode"),
            "title", v_str("Response Code"),
            "type", v_str("`$INTEGER`"),
            "format", v_str("int32")),
          cmap(3,
            "name", v_str("responseMessage"),
            "title", v_str("Response Message"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_update_profile"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/updateProfile"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("updateProfile"))),
                "parts", clist(1,
                  v_str("updateProfile")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(4,
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("header")))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "version", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("appName"),
            "title", v_str("App Name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("buildDate"),
            "title", v_str("Build Date"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("version"),
            "title", v_str("Version"),
            "type", v_str("`$STRING`"))),
        "name", v_str("version"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/version"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("version"))),
                "parts", clist(1,
                  v_str("version")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map())))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_audit_new(void);
Feature* feature_clienttrack_new(void);
Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_log_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_telemetry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
