package voxgig.bluefintecsuserbackofficesdk.core

import voxgig.bluefintecsuserbackofficesdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // 'by lazy' defaults to LazyThreadSafetyMode.SYNCHRONIZED, so concurrent
  // first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private val sharedConfigVal: MutableMap<String, Any?> by lazy { makeConfig() }

  fun sharedConfig(): MutableMap<String, Any?> = sharedConfigVal

  fun makeFeature(name: String): Feature {
    return when (name) {
      "audit" -> voxgig.bluefintecsuserbackofficesdk.feature.AuditFeature()
      "clienttrack" -> voxgig.bluefintecsuserbackofficesdk.feature.ClienttrackFeature()
      "debug" -> voxgig.bluefintecsuserbackofficesdk.feature.DebugFeature()
      "idempotency" -> voxgig.bluefintecsuserbackofficesdk.feature.IdempotencyFeature()
      "log" -> voxgig.bluefintecsuserbackofficesdk.feature.LogFeature()
      "metrics" -> voxgig.bluefintecsuserbackofficesdk.feature.MetricsFeature()
      "paging" -> voxgig.bluefintecsuserbackofficesdk.feature.PagingFeature()
      "ratelimit" -> voxgig.bluefintecsuserbackofficesdk.feature.RatelimitFeature()
      "retry" -> voxgig.bluefintecsuserbackofficesdk.feature.RetryFeature()
      "telemetry" -> voxgig.bluefintecsuserbackofficesdk.feature.TelemetryFeature()
      "test" -> voxgig.bluefintecsuserbackofficesdk.feature.TestFeature()
      "timeout" -> voxgig.bluefintecsuserbackofficesdk.feature.TimeoutFeature()
      else -> voxgig.bluefintecsuserbackofficesdk.feature.BaseFeature()
    }
  }

  // The plugin definitions the model selected per feature, as List<Any?>
  // so core need not name a feature's types. Empty when no active feature
  // declares active plugin groups for this target - and then no plugin
  // import is emitted either.
  private val featurePluginsMap: Map<String, List<Any?>> = mapOf(
  )

  // featurePlugins is the definitions list for one feature's chain.
  fun featurePlugins(name: String): List<Any?> = featurePluginsMap[name] ?: emptyList()

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsUserBackoffice\",")
    b.append("  \"slug\": \"bluefin-tecs-user-backoffice\",")
    b.append("  \"version\": \"0.1.1\",")
    b.append("  \"target\": \"kotlin\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"audit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"actor\": \"anonymous\",")
    b.append("    \"max\": 1000")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"sink\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"clienttrack\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"clientVersion\": \"0.0.1\"")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"clientName\": \"`\$STRING`\",")
    b.append("    \"clientVersion\": \"`\$STRING`\",")
    b.append("    \"headers\": \"`\$MAP`\",")
    b.append("    \"idgen\": \"`\$FUNCTION`\",")
    b.append("    \"sessionId\": \"`\$STRING`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"debug\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"max\": 100,")
    b.append("    \"redact\": [")
    b.append("     \"authorization\",")
    b.append("     \"cookie\",")
    b.append("     \"set-cookie\",")
    b.append("     \"api-key\",")
    b.append("     \"apikey\",")
    b.append("     \"x-api-key\",")
    b.append("     \"idempotency-key\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"onEntry\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"idempotency\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"header\": \"Idempotency-Key\",")
    b.append("    \"methods\": [")
    b.append("     \"POST\",")
    b.append("     \"PUT\",")
    b.append("     \"PATCH\",")
    b.append("     \"DELETE\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"create\",")
    b.append("     \"update\",")
    b.append("     \"remove\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"keygen\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"log\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": true")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"level\": \"`\$STRING`\",")
    b.append("    \"logger\": \"`\$ANY`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"metrics\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"paging\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"afterVar\": \"after\",")
    b.append("    \"cursorParam\": \"cursor\",")
    b.append("    \"firstVar\": \"first\",")
    b.append("    \"limitParam\": \"limit\",")
    b.append("    \"pageParam\": \"page\",")
    b.append("    \"startPage\": 1")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"limit\": \"`\$NUMBER`\",")
    b.append("    \"ops\": \"`\$LIST`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"ratelimit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"burst\": 5,")
    b.append("    \"rate\": 5")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"retry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"factor\": 2,")
    b.append("    \"maxDelay\": 2000,")
    b.append("    \"minDelay\": 50,")
    b.append("    \"retries\": 2,")
    b.append("    \"statuses\": [")
    b.append("     408,")
    b.append("     425,")
    b.append("     429,")
    b.append("     500,")
    b.append("     502,")
    b.append("     503,")
    b.append("     504")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"jitter\": \"`\$BOOLEAN`\",")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"telemetry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"exporter\": \"`\$FUNCTION`\",")
    b.append("    \"headers\": \"`\$MAP`\",")
    b.append("    \"idgen\": \"`\$FUNCTION`\",")
    b.append("    \"now\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"entity\": \"`\$MAP`\",")
    b.append("    \"net\": \"`\$MAP`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"base\"")
    b.append("  },")
    b.append("  \"timeout\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"ms\": 30000")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"clearTimer\": \"`\$FUNCTION`\",")
    b.append("    \"setTimer\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at/usermanagement-backofficews\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"output_activate_digital_module\": {},")
    b.append("   \"output_activate_portal_module\": {},")
    b.append("   \"output_activate_store_module\": {},")
    b.append("   \"output_activate_user\": {},")
    b.append("   \"output_assign_role\": {},")
    b.append("   \"output_change_logo\": {},")
    b.append("   \"output_create_mandator\": {},")
    b.append("   \"output_create_service_user\": {},")
    b.append("   \"output_deactivate_user\": {},")
    b.append("   \"output_get_kyc_document\": {},")
    b.append("   \"output_get_logo\": {},")
    b.append("   \"output_list_of_available_role\": {},")
    b.append("   \"output_list_of_mandator\": {},")
    b.append("   \"output_list_of_module\": {},")
    b.append("   \"output_list_of_role_group\": {},")
    b.append("   \"output_list_of_transactions_history\": {},")
    b.append("   \"output_list_of_user\": {},")
    b.append("   \"output_provide_credential\": {},")
    b.append("   \"output_register_user\": {},")
    b.append("   \"output_remove_role\": {},")
    b.append("   \"output_resend_link\": {},")
    b.append("   \"output_reset_password\": {},")
    b.append("   \"output_update_consumer\": {},")
    b.append("   \"output_update_profile\": {},")
    b.append("   \"version\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"output_activate_digital_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_digital_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateDigitalModule\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"activateDigitalModule\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"activateDigitalModule\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_portal_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"clientSecret\",")
    b.append("     \"title\": \"Client Secret\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"notificationEmail\",")
    b.append("     \"title\": \"Notification Email\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_portal_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateMerchantPortalModule\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"activateMerchantPortalModule\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"activateMerchantPortalModule\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_store_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_store_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateAppStoreModule\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"activateAppStoreModule\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"activateAppStoreModule\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_activate_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_activate_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/activateUser\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"activateUser\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"activateUser\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_assign_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier of the consumer (user) to whom the role(s) will be assigned.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"short\": \"Response code: 0 indicates success; any non-zero value indicates an error.\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"A human-readable message providing additional details about the outcome.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"roles\",")
    b.append("     \"title\": \"Roles\",")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"List of roles to assign to the consumer.\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_assign_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/assignRoles\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"assignRoles\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"assignRoles\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_change_logo\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"contentAsBase64\",")
    b.append("     \"title\": \"Content As Base64\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The content of the image as base64 encoded string\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mimeType\",")
    b.append("     \"title\": \"Mime Type\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The MIME type of the image\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_change_logo\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/changeLogo\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"changeLogo\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"changeLogo\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_create_mandator\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"city\",")
    b.append("     \"title\": \"City\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"title\": \"Country\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"title\": \"Date Of Birth\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"description\",")
    b.append("     \"title\": \"Description\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     }")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"driversLicenseNumber\",")
    b.append("     \"title\": \"Drivers License Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"title\": \"Email\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"title\": \"First Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"title\": \"Identification Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"title\": \"Last Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"login\",")
    b.append("     \"title\": \"Login\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"title\": \"Name\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     }")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"title\": \"Passport Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phone\",")
    b.append("     \"title\": \"Phone\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"salutation\",")
    b.append("     \"title\": \"Salutation\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"title\": \"State\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street1\",")
    b.append("     \"title\": \"Street1\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street2\",")
    b.append("     \"title\": \"Street2\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"zipCode\",")
    b.append("     \"title\": \"Zip Code\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_create_mandator\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/createMandator\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"createMandator\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"createMandator\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.mandator`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_create_service_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"mandatorName\",")
    b.append("     \"title\": \"Mandator Name\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_create_service_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/createServiceUser\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"createServiceUser\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"createServiceUser\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_deactivate_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_deactivate_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/deactivateUser\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"deactivateUser\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"deactivateUser\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_get_kyc_document\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"caseID\",")
    b.append("     \"title\": \"Case Id\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"encodedDataBase64\",")
    b.append("     \"title\": \"Encoded Data Base64\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_get_kyc_document\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/getKycDocument\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"getKycDocument\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"getKycDocument\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_get_logo\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"contentAsBase64\",")
    b.append("     \"title\": \"Content As Base64\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The content of the image as base64 encoded string\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mimeType\",")
    b.append("     \"title\": \"Mime Type\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The MIME type of the image\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_get_logo\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/getLogo\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"getLogo\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"getLogo\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_available_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"availableRoles\",")
    b.append("     \"title\": \"Available Roles\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_available_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfAvailableRoles\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfAvailableRoles\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfAvailableRoles\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_mandator\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"title\": \"Filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"list\",")
    b.append("     \"title\": \"List\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"title\": \"Pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"title\": \"Sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_mandator\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfMandators\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfMandators\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfMandators\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_module\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"list\",")
    b.append("     \"title\": \"List\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"title\": \"Pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_module\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfModules\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfModules\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfModules\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_role_group\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"title\": \"Filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"groupRoles\",")
    b.append("     \"title\": \"Group Roles\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"title\": \"Pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"title\": \"Sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_role_group\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfRoleGroups\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfRoleGroups\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfRoleGroups\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_transactions_history\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"title\": \"Filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"list\",")
    b.append("     \"title\": \"List\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"title\": \"Pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"title\": \"Sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_transactions_history\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfTransactionsHistory\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfTransactionsHistory\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfTransactionsHistory\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list_of_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"title\": \"Filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"list\",")
    b.append("     \"title\": \"List\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"title\": \"Pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"title\": \"Sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list_of_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/listOfUsers\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"listOfUsers\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"listOfUsers\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_provide_credential\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"mandatorName\",")
    b.append("     \"title\": \"Mandator Name\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"password\",")
    b.append("     \"title\": \"Password\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"username\",")
    b.append("     \"title\": \"Username\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_provide_credential\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/provideCredentials\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"provideCredentials\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"provideCredentials\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_register_user\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"city\",")
    b.append("     \"title\": \"City\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"City where the user resides.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"consumerId\",")
    b.append("     \"title\": \"Consumer Id\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User login or unique user identifier.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"consumerLanguage\",")
    b.append("     \"title\": \"Consumer Language\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Preferred language for the user (e.g., 'en').\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"title\": \"Country\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's country.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"title\": \"Date Of Birth\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's date of birth (expected format: dd.MM.yyyy).\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"driverLicenceNumber\",")
    b.append("     \"title\": \"Driver Licence Number\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's driver's license number.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"title\": \"Email\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"User's email address (must be unique).\",")
    b.append("     \"format\": \"email\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"title\": \"First Name\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's first name.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"title\": \"Identification Number\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's identification number.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"title\": \"Last Name\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's last name.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"login\",")
    b.append("     \"title\": \"Login\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User login identifier (should be unique).\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"module\",")
    b.append("     \"title\": \"Module\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Module identifier (if applicable).\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"title\": \"Passport Number\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's passport number.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phone\",")
    b.append("     \"title\": \"Phone\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's phone number.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"short\": \"Response code (0 indicates success; non-zero indicates an error).\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Human-readable response message.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"salutation\",")
    b.append("     \"title\": \"Salutation\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's salutation (e.g., Mr., Ms.).\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"title\": \"State\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"User's state or region.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street1\",")
    b.append("     \"title\": \"Street1\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Primary address line.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street2\",")
    b.append("     \"title\": \"Street2\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Secondary address line.\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"zip\",")
    b.append("     \"title\": \"Zip\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"short\": \"Postal code.\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_register_user\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/registerUser\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"registerUser\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"registerUser\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_remove_role\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"roles\",")
    b.append("     \"title\": \"Roles\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_remove_role\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/removeRoles\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"removeRoles\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"removeRoles\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_resend_link\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"businessRegistrationNumber\",")
    b.append("     \"title\": \"Business Registration Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"emailConfirmationCode\",")
    b.append("     \"title\": \"Email Confirmation Code\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"title\": \"Phone Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_resend_link\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/resendLink\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"resendLink\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"resendLink\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_reset_password\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUuid\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"title\": \"Phone Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_reset_password\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/resetPassword\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"resetPassword\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"resetPassword\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\",")
    b.append("          \"reqd\": true")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_update_consumer\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"city\",")
    b.append("     \"title\": \"City\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"consumerUuid\",")
    b.append("     \"title\": \"Consumer Uuid\",")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"req\": true")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"consumerlanguage\",")
    b.append("     \"title\": \"Consumerlanguage\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"title\": \"Country\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"dateOfBirth\",")
    b.append("     \"title\": \"Date Of Birth\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"datetime_created\",")
    b.append("     \"title\": \"Datetime Created\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"driverLicenceNumber\",")
    b.append("     \"title\": \"Driver Licence Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"title\": \"Email\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"title\": \"First Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"identificationNumber\",")
    b.append("     \"title\": \"Identification Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"kycPassed\",")
    b.append("     \"title\": \"Kyc Passed\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"title\": \"Last Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"nationality\",")
    b.append("     \"title\": \"Nationality\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"passportNumber\",")
    b.append("     \"title\": \"Passport Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"title\": \"Phone Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"placeOfBirth\",")
    b.append("     \"title\": \"Place Of Birth\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"title\": \"State\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street1\",")
    b.append("     \"title\": \"Street1\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street2\",")
    b.append("     \"title\": \"Street2\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transactionhistory_id\",")
    b.append("     \"title\": \"Transactionhistory Id\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"zip\",")
    b.append("     \"title\": \"Zip\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_update_consumer\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/updateConsumer\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"updateConsumer\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"updateConsumer\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_update_profile\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerLanguage\",")
    b.append("     \"title\": \"Consumer Language\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"title\": \"Email\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"firstName\",")
    b.append("     \"title\": \"First Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lastName\",")
    b.append("     \"title\": \"Last Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"title\": \"Phone Number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"title\": \"Response Code\",")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"format\": \"int32\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"title\": \"Response Message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_update_profile\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/updateProfile\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"updateProfile\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"updateProfile\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\",")
    b.append("          \"kind\": \"header\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"version\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"appName\",")
    b.append("     \"title\": \"App Name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"buildDate\",")
    b.append("     \"title\": \"Build Date\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"version\",")
    b.append("     \"title\": \"Version\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"version\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/version\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"version\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"parts\": [")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"rename\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"args\": {},")
    b.append("       \"select\": {}")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
