// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/bluefin-tecs-user-backoffice-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"output_activate_digital_module | output_activate_portal_module | output_activate_store_module | output_activate_user | output_assign_role | output_change_logo | output_create_mandator | output_create_service_user | output_deactivate_user | output_get_kyc_document | output_get_logo | output_list_of_available_role | output_list_of_mandator | output_list_of_module | output_list_of_role_group | output_list_of_transactions_history | output_list_of_user | output_provide_credential | output_register_user | output_remove_role | output_resend_link | output_reset_password | output_update_consumer | output_update_profile | version"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.BluefinTecsUserBackofficeSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-user-backoffice_list",
		Description: "List records from BluefinTecsUserBackoffice. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-user-backoffice_load",
		Description: "Load a single record from BluefinTecsUserBackoffice. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.BluefinTecsUserBackofficeSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinTecsUserBackofficeSDK, name string) (sdk.BluefinTecsUserBackofficeEntity, error) {
	switch strings.ToLower(name) {
	case "output_activate_digital_module":
		return client.OutputActivateDigitalModule(nil), nil
	case "output_activate_portal_module":
		return client.OutputActivatePortalModule(nil), nil
	case "output_activate_store_module":
		return client.OutputActivateStoreModule(nil), nil
	case "output_activate_user":
		return client.OutputActivateUser(nil), nil
	case "output_assign_role":
		return client.OutputAssignRole(nil), nil
	case "output_change_logo":
		return client.OutputChangeLogo(nil), nil
	case "output_create_mandator":
		return client.OutputCreateMandator(nil), nil
	case "output_create_service_user":
		return client.OutputCreateServiceUser(nil), nil
	case "output_deactivate_user":
		return client.OutputDeactivateUser(nil), nil
	case "output_get_kyc_document":
		return client.OutputGetKycDocument(nil), nil
	case "output_get_logo":
		return client.OutputGetLogo(nil), nil
	case "output_list_of_available_role":
		return client.OutputListOfAvailableRole(nil), nil
	case "output_list_of_mandator":
		return client.OutputListOfMandator(nil), nil
	case "output_list_of_module":
		return client.OutputListOfModule(nil), nil
	case "output_list_of_role_group":
		return client.OutputListOfRoleGroup(nil), nil
	case "output_list_of_transactions_history":
		return client.OutputListOfTransactionsHistory(nil), nil
	case "output_list_of_user":
		return client.OutputListOfUser(nil), nil
	case "output_provide_credential":
		return client.OutputProvideCredential(nil), nil
	case "output_register_user":
		return client.OutputRegisterUser(nil), nil
	case "output_remove_role":
		return client.OutputRemoveRole(nil), nil
	case "output_resend_link":
		return client.OutputResendLink(nil), nil
	case "output_reset_password":
		return client.OutputResetPassword(nil), nil
	case "output_update_consumer":
		return client.OutputUpdateConsumer(nil), nil
	case "output_update_profile":
		return client.OutputUpdateProfile(nil), nil
	case "version":
		return client.Version(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
