(* BluefinTecsUserBackoffice SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* OutputActivateDigitalModule entity bound to a client:  output_activate_digital_module client entopts *)
let output_activate_digital_module (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_activate_digital_module.make client entopts

(* OutputActivatePortalModule entity bound to a client:  output_activate_portal_module client entopts *)
let output_activate_portal_module (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_activate_portal_module.make client entopts

(* OutputActivateStoreModule entity bound to a client:  output_activate_store_module client entopts *)
let output_activate_store_module (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_activate_store_module.make client entopts

(* OutputActivateUser entity bound to a client:  output_activate_user client entopts *)
let output_activate_user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_activate_user.make client entopts

(* OutputAssignRole entity bound to a client:  output_assign_role client entopts *)
let output_assign_role (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_assign_role.make client entopts

(* OutputChangeLogo entity bound to a client:  output_change_logo client entopts *)
let output_change_logo (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_change_logo.make client entopts

(* OutputCreateMandator entity bound to a client:  output_create_mandator client entopts *)
let output_create_mandator (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_create_mandator.make client entopts

(* OutputCreateServiceUser entity bound to a client:  output_create_service_user client entopts *)
let output_create_service_user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_create_service_user.make client entopts

(* OutputDeactivateUser entity bound to a client:  output_deactivate_user client entopts *)
let output_deactivate_user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_deactivate_user.make client entopts

(* OutputGetKycDocument entity bound to a client:  output_get_kyc_document client entopts *)
let output_get_kyc_document (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_get_kyc_document.make client entopts

(* OutputGetLogo entity bound to a client:  output_get_logo client entopts *)
let output_get_logo (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_get_logo.make client entopts

(* OutputListOfAvailableRole entity bound to a client:  output_list_of_available_role client entopts *)
let output_list_of_available_role (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_available_role.make client entopts

(* OutputListOfMandator entity bound to a client:  output_list_of_mandator client entopts *)
let output_list_of_mandator (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_mandator.make client entopts

(* OutputListOfModule entity bound to a client:  output_list_of_module client entopts *)
let output_list_of_module (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_module.make client entopts

(* OutputListOfRoleGroup entity bound to a client:  output_list_of_role_group client entopts *)
let output_list_of_role_group (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_role_group.make client entopts

(* OutputListOfTransactionsHistory entity bound to a client:  output_list_of_transactions_history client entopts *)
let output_list_of_transactions_history (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_transactions_history.make client entopts

(* OutputListOfUser entity bound to a client:  output_list_of_user client entopts *)
let output_list_of_user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list_of_user.make client entopts

(* OutputProvideCredential entity bound to a client:  output_provide_credential client entopts *)
let output_provide_credential (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_provide_credential.make client entopts

(* OutputRegisterUser entity bound to a client:  output_register_user client entopts *)
let output_register_user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_register_user.make client entopts

(* OutputRemoveRole entity bound to a client:  output_remove_role client entopts *)
let output_remove_role (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_remove_role.make client entopts

(* OutputResendLink entity bound to a client:  output_resend_link client entopts *)
let output_resend_link (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_resend_link.make client entopts

(* OutputResetPassword entity bound to a client:  output_reset_password client entopts *)
let output_reset_password (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_reset_password.make client entopts

(* OutputUpdateConsumer entity bound to a client:  output_update_consumer client entopts *)
let output_update_consumer (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_update_consumer.make client entopts

(* OutputUpdateProfile entity bound to a client:  output_update_profile client entopts *)
let output_update_profile (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_update_profile.make client entopts

(* Version entity bound to a client:  version client entopts *)
let version (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_version.make client entopts
