-- BluefinTecsUserBackoffice SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , output_activate_digital_module
  , output_activate_portal_module
  , output_activate_store_module
  , output_activate_user
  , output_assign_role
  , output_change_logo
  , output_create_mandator
  , output_create_service_user
  , output_deactivate_user
  , output_get_kyc_document
  , output_get_logo
  , output_list_of_available_role
  , output_list_of_mandator
  , output_list_of_module
  , output_list_of_role_group
  , output_list_of_transactions_history
  , output_list_of_user
  , output_provide_credential
  , output_register_user
  , output_remove_role
  , output_resend_link
  , output_reset_password
  , output_update_consumer
  , output_update_profile
  , version
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The OutputActivateDigitalModule entity bound to this client.
output_activate_digital_module :: Client -> Value -> IO Entity
output_activate_digital_module client entopts = F.makeEntity client "output_activate_digital_module" entopts

-- | The OutputActivatePortalModule entity bound to this client.
output_activate_portal_module :: Client -> Value -> IO Entity
output_activate_portal_module client entopts = F.makeEntity client "output_activate_portal_module" entopts

-- | The OutputActivateStoreModule entity bound to this client.
output_activate_store_module :: Client -> Value -> IO Entity
output_activate_store_module client entopts = F.makeEntity client "output_activate_store_module" entopts

-- | The OutputActivateUser entity bound to this client.
output_activate_user :: Client -> Value -> IO Entity
output_activate_user client entopts = F.makeEntity client "output_activate_user" entopts

-- | The OutputAssignRole entity bound to this client.
output_assign_role :: Client -> Value -> IO Entity
output_assign_role client entopts = F.makeEntity client "output_assign_role" entopts

-- | The OutputChangeLogo entity bound to this client.
output_change_logo :: Client -> Value -> IO Entity
output_change_logo client entopts = F.makeEntity client "output_change_logo" entopts

-- | The OutputCreateMandator entity bound to this client.
output_create_mandator :: Client -> Value -> IO Entity
output_create_mandator client entopts = F.makeEntity client "output_create_mandator" entopts

-- | The OutputCreateServiceUser entity bound to this client.
output_create_service_user :: Client -> Value -> IO Entity
output_create_service_user client entopts = F.makeEntity client "output_create_service_user" entopts

-- | The OutputDeactivateUser entity bound to this client.
output_deactivate_user :: Client -> Value -> IO Entity
output_deactivate_user client entopts = F.makeEntity client "output_deactivate_user" entopts

-- | The OutputGetKycDocument entity bound to this client.
output_get_kyc_document :: Client -> Value -> IO Entity
output_get_kyc_document client entopts = F.makeEntity client "output_get_kyc_document" entopts

-- | The OutputGetLogo entity bound to this client.
output_get_logo :: Client -> Value -> IO Entity
output_get_logo client entopts = F.makeEntity client "output_get_logo" entopts

-- | The OutputListOfAvailableRole entity bound to this client.
output_list_of_available_role :: Client -> Value -> IO Entity
output_list_of_available_role client entopts = F.makeEntity client "output_list_of_available_role" entopts

-- | The OutputListOfMandator entity bound to this client.
output_list_of_mandator :: Client -> Value -> IO Entity
output_list_of_mandator client entopts = F.makeEntity client "output_list_of_mandator" entopts

-- | The OutputListOfModule entity bound to this client.
output_list_of_module :: Client -> Value -> IO Entity
output_list_of_module client entopts = F.makeEntity client "output_list_of_module" entopts

-- | The OutputListOfRoleGroup entity bound to this client.
output_list_of_role_group :: Client -> Value -> IO Entity
output_list_of_role_group client entopts = F.makeEntity client "output_list_of_role_group" entopts

-- | The OutputListOfTransactionsHistory entity bound to this client.
output_list_of_transactions_history :: Client -> Value -> IO Entity
output_list_of_transactions_history client entopts = F.makeEntity client "output_list_of_transactions_history" entopts

-- | The OutputListOfUser entity bound to this client.
output_list_of_user :: Client -> Value -> IO Entity
output_list_of_user client entopts = F.makeEntity client "output_list_of_user" entopts

-- | The OutputProvideCredential entity bound to this client.
output_provide_credential :: Client -> Value -> IO Entity
output_provide_credential client entopts = F.makeEntity client "output_provide_credential" entopts

-- | The OutputRegisterUser entity bound to this client.
output_register_user :: Client -> Value -> IO Entity
output_register_user client entopts = F.makeEntity client "output_register_user" entopts

-- | The OutputRemoveRole entity bound to this client.
output_remove_role :: Client -> Value -> IO Entity
output_remove_role client entopts = F.makeEntity client "output_remove_role" entopts

-- | The OutputResendLink entity bound to this client.
output_resend_link :: Client -> Value -> IO Entity
output_resend_link client entopts = F.makeEntity client "output_resend_link" entopts

-- | The OutputResetPassword entity bound to this client.
output_reset_password :: Client -> Value -> IO Entity
output_reset_password client entopts = F.makeEntity client "output_reset_password" entopts

-- | The OutputUpdateConsumer entity bound to this client.
output_update_consumer :: Client -> Value -> IO Entity
output_update_consumer client entopts = F.makeEntity client "output_update_consumer" entopts

-- | The OutputUpdateProfile entity bound to this client.
output_update_profile :: Client -> Value -> IO Entity
output_update_profile client entopts = F.makeEntity client "output_update_profile" entopts

-- | The Version entity bound to this client.
version :: Client -> Value -> IO Entity
version client entopts = F.makeEntity client "version" entopts

