-- BluefinTecsUserBackoffice SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    pure ()
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      pure ()
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
