;; BluefinTecsUserBackoffice SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.output_activate_digital_module :as e-output_activate_digital_module]
            [sdk.entity.output_activate_portal_module :as e-output_activate_portal_module]
            [sdk.entity.output_activate_store_module :as e-output_activate_store_module]
            [sdk.entity.output_activate_user :as e-output_activate_user]
            [sdk.entity.output_assign_role :as e-output_assign_role]
            [sdk.entity.output_change_logo :as e-output_change_logo]
            [sdk.entity.output_create_mandator :as e-output_create_mandator]
            [sdk.entity.output_create_service_user :as e-output_create_service_user]
            [sdk.entity.output_deactivate_user :as e-output_deactivate_user]
            [sdk.entity.output_get_kyc_document :as e-output_get_kyc_document]
            [sdk.entity.output_get_logo :as e-output_get_logo]
            [sdk.entity.output_list_of_available_role :as e-output_list_of_available_role]
            [sdk.entity.output_list_of_mandator :as e-output_list_of_mandator]
            [sdk.entity.output_list_of_module :as e-output_list_of_module]
            [sdk.entity.output_list_of_role_group :as e-output_list_of_role_group]
            [sdk.entity.output_list_of_transactions_history :as e-output_list_of_transactions_history]
            [sdk.entity.output_list_of_user :as e-output_list_of_user]
            [sdk.entity.output_provide_credential :as e-output_provide_credential]
            [sdk.entity.output_register_user :as e-output_register_user]
            [sdk.entity.output_remove_role :as e-output_remove_role]
            [sdk.entity.output_resend_link :as e-output_resend_link]
            [sdk.entity.output_reset_password :as e-output_reset_password]
            [sdk.entity.output_update_consumer :as e-output_update_consumer]
            [sdk.entity.output_update_profile :as e-output_update_profile]
            [sdk.entity.version :as e-version]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; OutputActivateDigitalModule accessor: (output_activate_digital_module client data)
(defn output_activate_digital_module [client data] (e-output_activate_digital_module/make client data))

;; OutputActivatePortalModule accessor: (output_activate_portal_module client data)
(defn output_activate_portal_module [client data] (e-output_activate_portal_module/make client data))

;; OutputActivateStoreModule accessor: (output_activate_store_module client data)
(defn output_activate_store_module [client data] (e-output_activate_store_module/make client data))

;; OutputActivateUser accessor: (output_activate_user client data)
(defn output_activate_user [client data] (e-output_activate_user/make client data))

;; OutputAssignRole accessor: (output_assign_role client data)
(defn output_assign_role [client data] (e-output_assign_role/make client data))

;; OutputChangeLogo accessor: (output_change_logo client data)
(defn output_change_logo [client data] (e-output_change_logo/make client data))

;; OutputCreateMandator accessor: (output_create_mandator client data)
(defn output_create_mandator [client data] (e-output_create_mandator/make client data))

;; OutputCreateServiceUser accessor: (output_create_service_user client data)
(defn output_create_service_user [client data] (e-output_create_service_user/make client data))

;; OutputDeactivateUser accessor: (output_deactivate_user client data)
(defn output_deactivate_user [client data] (e-output_deactivate_user/make client data))

;; OutputGetKycDocument accessor: (output_get_kyc_document client data)
(defn output_get_kyc_document [client data] (e-output_get_kyc_document/make client data))

;; OutputGetLogo accessor: (output_get_logo client data)
(defn output_get_logo [client data] (e-output_get_logo/make client data))

;; OutputListOfAvailableRole accessor: (output_list_of_available_role client data)
(defn output_list_of_available_role [client data] (e-output_list_of_available_role/make client data))

;; OutputListOfMandator accessor: (output_list_of_mandator client data)
(defn output_list_of_mandator [client data] (e-output_list_of_mandator/make client data))

;; OutputListOfModule accessor: (output_list_of_module client data)
(defn output_list_of_module [client data] (e-output_list_of_module/make client data))

;; OutputListOfRoleGroup accessor: (output_list_of_role_group client data)
(defn output_list_of_role_group [client data] (e-output_list_of_role_group/make client data))

;; OutputListOfTransactionsHistory accessor: (output_list_of_transactions_history client data)
(defn output_list_of_transactions_history [client data] (e-output_list_of_transactions_history/make client data))

;; OutputListOfUser accessor: (output_list_of_user client data)
(defn output_list_of_user [client data] (e-output_list_of_user/make client data))

;; OutputProvideCredential accessor: (output_provide_credential client data)
(defn output_provide_credential [client data] (e-output_provide_credential/make client data))

;; OutputRegisterUser accessor: (output_register_user client data)
(defn output_register_user [client data] (e-output_register_user/make client data))

;; OutputRemoveRole accessor: (output_remove_role client data)
(defn output_remove_role [client data] (e-output_remove_role/make client data))

;; OutputResendLink accessor: (output_resend_link client data)
(defn output_resend_link [client data] (e-output_resend_link/make client data))

;; OutputResetPassword accessor: (output_reset_password client data)
(defn output_reset_password [client data] (e-output_reset_password/make client data))

;; OutputUpdateConsumer accessor: (output_update_consumer client data)
(defn output_update_consumer [client data] (e-output_update_consumer/make client data))

;; OutputUpdateProfile accessor: (output_update_profile client data)
(defn output_update_profile [client data] (e-output_update_profile/make client data))

;; Version accessor: (version client data)
(defn version [client data] (e-version/make client data))
