;; BluefinTecsUserBackoffice SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "output_activate_digital_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_activate_digital_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/activateDigitalModule"
                "parts" (vs/jt
                  "activateDigitalModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_portal_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client_secret"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "notification_email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_activate_portal_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/activateMerchantPortalModule"
                "parts" (vs/jt
                  "activateMerchantPortalModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_store_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_activate_store_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/activateAppStoreModule"
                "parts" (vs/jt
                  "activateAppStoreModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_activate_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/activateUser"
                "parts" (vs/jt
                  "activateUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_assign_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "role"
            "req" true
            "type" "`$ARRAY`"))
        "name" "output_assign_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/assignRoles"
                "parts" (vs/jt
                  "assignRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_change_logo" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "content_as_base64"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "mime_type"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_change_logo"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/changeLogo"
                "parts" (vs/jt
                  "changeLogo")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_mandator" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "city"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "country"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "date_of_birth"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "description"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "drivers_license_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "first_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "identification_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "last_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "login"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "mandator"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "passport_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "phone"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "salutation"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "state"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "street1"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "street2"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 20
            "name" "zip_code"
            "req" false
            "type" "`$STRING`"))
        "name" "output_create_mandator"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/createMandator"
                "parts" (vs/jt
                  "createMandator")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_service_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "mandator_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_create_service_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/createServiceUser"
                "parts" (vs/jt
                  "createServiceUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_deactivate_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_deactivate_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/deactivateUser"
                "parts" (vs/jt
                  "deactivateUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_get_kyc_document" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "case_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "encoded_data_base64"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_get_kyc_document"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/getKycDocument"
                "parts" (vs/jt
                  "getKycDocument")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_get_logo" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "content_as_base64"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "mime_type"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_get_logo"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/getLogo"
                "parts" (vs/jt
                  "getLogo")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_available_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "available_role"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_list_of_available_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfAvailableRoles"
                "parts" (vs/jt
                  "listOfAvailableRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_mandator" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "list"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "output_list_of_mandator"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfMandators"
                "parts" (vs/jt
                  "listOfMandators")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "list"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_list_of_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfModules"
                "parts" (vs/jt
                  "listOfModules")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_role_group" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "group_role"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "output_list_of_role_group"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfRoleGroups"
                "parts" (vs/jt
                  "listOfRoleGroups")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_transactions_history" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "list"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "output_list_of_transactions_history"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfTransactionsHistory"
                "parts" (vs/jt
                  "listOfTransactionsHistory")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "list"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "output_list_of_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/listOfUsers"
                "parts" (vs/jt
                  "listOfUsers")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_provide_credential" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "mandator_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "password"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "username"
            "req" false
            "type" "`$STRING`"))
        "name" "output_provide_credential"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/provideCredentials"
                "parts" (vs/jt
                  "provideCredentials")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_register_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "city"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "consumer_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "consumer_language"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "country"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "date_of_birth"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "driver_licence_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "first_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "identification_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "last_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "login"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "module"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "passport_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "phone"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "salutation"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "state"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "street1"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "street2"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 20
            "name" "zip"
            "req" false
            "type" "`$STRING`"))
        "name" "output_register_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/registerUser"
                "parts" (vs/jt
                  "registerUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_remove_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "role"
            "req" false
            "type" "`$ARRAY`"))
        "name" "output_remove_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/removeRoles"
                "parts" (vs/jt
                  "removeRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_resend_link" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "business_registration_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "consumer_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "email_confirmation_code"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_resend_link"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/resendLink"
                "parts" (vs/jt
                  "resendLink")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_reset_password" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_reset_password"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/resetPassword"
                "parts" (vs/jt
                  "resetPassword")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_consumer" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "city"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "consumer_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "consumerlanguage"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "country"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "date_of_birth"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "datetime_created"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "driver_licence_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "first_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "identification_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "kyc_passed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "last_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "nationality"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "passport_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "place_of_birth"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "response_message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "state"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "street1"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 20
            "name" "street2"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 21
            "name" "transactionhistory_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 22
            "name" "zip"
            "req" false
            "type" "`$STRING`"))
        "name" "output_update_consumer"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/updateConsumer"
                "parts" (vs/jt
                  "updateConsumer")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_profile" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_language"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "first_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "last_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "response_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "response_message"
            "req" false
            "type" "`$STRING`"))
        "name" "output_update_profile"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/updateProfile"
                "parts" (vs/jt
                  "updateProfile")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "version" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "app_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "build_date"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "version"
            "req" false
            "type" "`$STRING`"))
        "name" "version"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "GET"
                "orig" "/version"
                "parts" (vs/jt
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinTecsUserBackoffice")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://test.tecs.at/usermanagement-backofficews"
      "entity" (vs/jm
        "output_activate_digital_module" (vs/jm)
        "output_activate_portal_module" (vs/jm)
        "output_activate_store_module" (vs/jm)
        "output_activate_user" (vs/jm)
        "output_assign_role" (vs/jm)
        "output_change_logo" (vs/jm)
        "output_create_mandator" (vs/jm)
        "output_create_service_user" (vs/jm)
        "output_deactivate_user" (vs/jm)
        "output_get_kyc_document" (vs/jm)
        "output_get_logo" (vs/jm)
        "output_list_of_available_role" (vs/jm)
        "output_list_of_mandator" (vs/jm)
        "output_list_of_module" (vs/jm)
        "output_list_of_role_group" (vs/jm)
        "output_list_of_transactions_history" (vs/jm)
        "output_list_of_user" (vs/jm)
        "output_provide_credential" (vs/jm)
        "output_register_user" (vs/jm)
        "output_remove_role" (vs/jm)
        "output_resend_link" (vs/jm)
        "output_reset_password" (vs/jm)
        "output_update_consumer" (vs/jm)
        "output_update_profile" (vs/jm)
        "version" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
