;; BluefinTecsUserBackoffice SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "output_activate_digital_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_activate_digital_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/activateDigitalModule"
                "parts" (vs/jt
                  "activateDigitalModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_portal_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clientSecret"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "notificationEmail"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_activate_portal_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/activateMerchantPortalModule"
                "parts" (vs/jt
                  "activateMerchantPortalModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_store_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_activate_store_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/activateAppStoreModule"
                "parts" (vs/jt
                  "activateAppStoreModule")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_activate_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_activate_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/activateUser"
                "parts" (vs/jt
                  "activateUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_assign_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "roles"
            "req" true
            "type" "`$ARRAY`"))
        "name" "output_assign_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/assignRoles"
                "parts" (vs/jt
                  "assignRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_change_logo" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "contentAsBase64"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "mimeType"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_change_logo"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/changeLogo"
                "parts" (vs/jt
                  "changeLogo")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_mandator" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateOfBirth"
            "type" "`$STRING`")
          (vs/jm
            "name" "description"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "driversLicenseNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "identificationNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "login"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "passportNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "phone"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "salutation"
            "type" "`$STRING`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "street1"
            "type" "`$STRING`")
          (vs/jm
            "name" "street2"
            "type" "`$STRING`")
          (vs/jm
            "name" "zipCode"
            "type" "`$STRING`"))
        "name" "output_create_mandator"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/createMandator"
                "parts" (vs/jt
                  "createMandator")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_service_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "mandatorName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_create_service_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/createServiceUser"
                "parts" (vs/jt
                  "createServiceUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_deactivate_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_deactivate_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/deactivateUser"
                "parts" (vs/jt
                  "deactivateUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_get_kyc_document" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "caseID"
            "type" "`$STRING`")
          (vs/jm
            "name" "encodedDataBase64"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_get_kyc_document"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/getKycDocument"
                "parts" (vs/jt
                  "getKycDocument")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_get_logo" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "contentAsBase64"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "mimeType"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_get_logo"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/getLogo"
                "parts" (vs/jt
                  "getLogo")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_available_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "availableRoles"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_list_of_available_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfAvailableRoles"
                "parts" (vs/jt
                  "listOfAvailableRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_mandator" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "list"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "output_list_of_mandator"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfMandators"
                "parts" (vs/jt
                  "listOfMandators")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_module" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "list"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_list_of_module"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfModules"
                "parts" (vs/jt
                  "listOfModules")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_role_group" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "groupRoles"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "output_list_of_role_group"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfRoleGroups"
                "parts" (vs/jt
                  "listOfRoleGroups")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_transactions_history" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "list"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "output_list_of_transactions_history"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfTransactionsHistory"
                "parts" (vs/jt
                  "listOfTransactionsHistory")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list_of_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "list"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "output_list_of_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/listOfUsers"
                "parts" (vs/jt
                  "listOfUsers")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_provide_credential" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "mandatorName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "username"
            "type" "`$STRING`"))
        "name" "output_provide_credential"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/provideCredentials"
                "parts" (vs/jt
                  "provideCredentials")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_register_user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "consumerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "consumerLanguage"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateOfBirth"
            "type" "`$STRING`")
          (vs/jm
            "name" "driverLicenceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "identificationNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "login"
            "type" "`$STRING`")
          (vs/jm
            "name" "module"
            "type" "`$STRING`")
          (vs/jm
            "name" "passportNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "phone"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "salutation"
            "type" "`$STRING`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "street1"
            "type" "`$STRING`")
          (vs/jm
            "name" "street2"
            "type" "`$STRING`")
          (vs/jm
            "name" "zip"
            "type" "`$STRING`"))
        "name" "output_register_user"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/registerUser"
                "parts" (vs/jt
                  "registerUser")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_remove_role" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "roles"
            "type" "`$ARRAY`"))
        "name" "output_remove_role"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/removeRoles"
                "parts" (vs/jt
                  "removeRoles")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_resend_link" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "businessRegistrationNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "consumerUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "emailConfirmationCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "phoneNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_resend_link"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/resendLink"
                "parts" (vs/jt
                  "resendLink")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_reset_password" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "phoneNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_reset_password"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/resetPassword"
                "parts" (vs/jt
                  "resetPassword")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_consumer" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "consumerUuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "consumerlanguage"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateOfBirth"
            "type" "`$STRING`")
          (vs/jm
            "name" "datetime_created"
            "type" "`$STRING`")
          (vs/jm
            "name" "driverLicenceNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "identificationNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "kycPassed"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "nationality"
            "type" "`$STRING`")
          (vs/jm
            "name" "passportNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "phoneNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "placeOfBirth"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "street1"
            "type" "`$STRING`")
          (vs/jm
            "name" "street2"
            "type" "`$STRING`")
          (vs/jm
            "name" "transactionhistory_id"
            "type" "`$STRING`")
          (vs/jm
            "name" "zip"
            "type" "`$STRING`"))
        "name" "output_update_consumer"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/updateConsumer"
                "parts" (vs/jt
                  "updateConsumer")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_profile" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerLanguage"
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "phoneNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "type" "`$STRING`"))
        "name" "output_update_profile"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/updateProfile"
                "parts" (vs/jt
                  "updateProfile")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "version" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appName"
            "type" "`$STRING`")
          (vs/jm
            "name" "buildDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$STRING`"))
        "name" "version"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/version"
                "parts" (vs/jt
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinTecsUserBackoffice")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://test.tecs.at/usermanagement-backofficews"
      "entity" (vs/jm
        "output_activate_digital_module" (vs/jm)
        "output_activate_portal_module" (vs/jm)
        "output_activate_store_module" (vs/jm)
        "output_activate_user" (vs/jm)
        "output_assign_role" (vs/jm)
        "output_change_logo" (vs/jm)
        "output_create_mandator" (vs/jm)
        "output_create_service_user" (vs/jm)
        "output_deactivate_user" (vs/jm)
        "output_get_kyc_document" (vs/jm)
        "output_get_logo" (vs/jm)
        "output_list_of_available_role" (vs/jm)
        "output_list_of_mandator" (vs/jm)
        "output_list_of_module" (vs/jm)
        "output_list_of_role_group" (vs/jm)
        "output_list_of_transactions_history" (vs/jm)
        "output_list_of_user" (vs/jm)
        "output_provide_credential" (vs/jm)
        "output_register_user" (vs/jm)
        "output_remove_role" (vs/jm)
        "output_resend_link" (vs/jm)
        "output_reset_password" (vs/jm)
        "output_update_consumer" (vs/jm)
        "output_update_profile" (vs/jm)
        "version" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
